### ISSUE TITLE
incorrect requires version in version.php

### ISSUE THREAD

**Issue by danmarsden** [Svenwas3f/moodle-quiz_exportresults#3]
I'm pretty sure the version you have set in your version.php for the "requires" version is incorrect and the moodle.org plugins db entry lists your plugin as supporting Moodle 2.7 -> 4.0 Have you really tested this in Moodle 2.7? 

can you please confirm which versions you have tested this with and fix up the requires version to reflect this?
https://github.com/Svenwas3f/moodle-quiz_exportresults/blob/master/version.php#L27

I suspect it's more likely you've tested this in Moodle 3.9 and higher...

**Comment by Svenwas3f** [comment]
Thanks for your feedback. I found this error aswell but couldn't locate it (It's the first time i work with moodle). It would have been a easy fix if I understand you correctly. My development environment runs moodle 3.11 but I know that it works aswell in moodle 3.9 (Other development environment). Therefore I changed the value of the variable $plugin->requires into 2020061500.
